### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by marriazevedo** [dmcpatrimonio/arqtrad#10]
### Carta de motivação

Meu nome é Mariana de Fátima Macedo Nunes de Azevedo, tenho 22 anos e sou graduanda do 8º semestre de Arquitetura e Urbanismo pela Universidade de Brasília. Venho por meio desta apresentar minha carta de motivação para o projeto de pesquisa coordenado por Pedro Paulo Palazzo, do grupo de pesquisa Documentação, Modelagem e Conservação do Patrimônio.
O patrimônio de Luziânia tem diminuído constantemente ao passar dos anos, restando pouco para contar a história da cidade. Muitas edificações históricas foram demolidas, algumas apresentam estado de abandono e falta de manutenção, outras passaram por alterações não condizentes com estilo arquitetônico. Além disso, os exemplares restantes desse período, progressivamente se configuram de modo unitário, perdendo um conjunto sólido que os reúna. O PIBIC é um esforço para resguardar a memória da cidade, criar registros e contribuir para valorização do patrimônio.

Nascida dentro do Distrito Federal, mas criada e vivida em Luziânia, sempre existiu em mim o interesse em empregar os conhecimentos que viesse a ter em prol da cidade e de sua memória. A primeira oportunidade ocorreu na disciplina de Arquitetura e Urbanismo no Brasil Colônia e Império, em que me propus a fazer, em um dos trabalhos, o levantamento da Casa da Cultura, localizada na rua do Rosário. Este foi também o ponto inicial da iniciativa de pesquisa.

Minhas qualificações em pesquisas restringem-se aos trabalhos em disciplinas da graduação, não sendo muito recorrentes ou aprofundados, mas considero esta uma oportunidade única para adquirir aprendizados que ultrapassam qualquer outra disciplina. Apesar de não possuir projetos de pesquisas, vivenciei outras atividades na graduação, como cursos na semana universitária, monitoria na disciplina de Planejamento Urbano, ministrada pelo professor Benny Schvarsberg e, ainda, colaboração no projeto de extensão do ATHOS para Melhorias Habitacionais, coordenado pela professora Cristiane Guinancio. Outrossim, estive em 7 Encontros de Estudantes de Arquitetura e Urbanismo – EREA e 1 encontro nacional - ENEA, cada qual em um local diferente do país, nos quais ocorreram mesas de debate e vivências nas cidades a respeito de patrimônio, tendo como destaque o EREA Piri, ocorrido em Pirenópolis/GO, o qual possuía a história como pilar principal.

### Links

- http://lattes.cnpq.br/4452882297765384# 
- http://orcid.org/0000-0003-0476-6962

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [ ] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [ ] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [X] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Olá Mariana,

Obrigado pelo interesse continuado. Estamos apostando numa proposta de dados abertos e colaborativos, por isso vamos continuar trabalhando aqui na plataforma GitHub. Para inscrever o plano de trabalho na seleção, precisamos completá-lo com metodologia, bibliografia e cronograma.

O rascunho do plano de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponível para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/) (Essa é a oportunidade "convencional"; se quiseres trabalhar de fato com os arquivos do Itamaraty, vamos conversando para formular um plano de trabalho especial).

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)
