### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by Iriani11** [dmcpatrimonio/arqtrad#17]
### Carta de motivação

Por ter grande interesse na área de historiografia, em específico nas técnicas construtivas que se moldaram aos recursos que estavam à disposição no local e época da construção, assim como na área de pesquisa, decidi tomar o primeiro passo para atuar nessa área. Após algumas recomendações e analises, me interessei pela pesquisa “Resiliência urbana: Estratégias adaptativas na construção tradicional”, de sua autoria, especificamente por se tratar também de uma analise gradual evolutiva. 
Tendo como base na área de pesquisa na qual eu mais me identifico, como também na linha de estudo que se trata a sua pesquisa, tomei a iniciativa de fazer um PIBIC. A pesquisa teria como base um estudo no método construtivo assim como na morfologia das construções, visando alguns aspectos como: os recursos, o clima, a topografia, entre outros. Nesse processo seriam identificados como e quais recursos, que estavam disponíveis naquela ocasião, foram utilizados na construção e identificando quais que foram utilizados de forma errônea, por não terem sido estudados frente às adversidades que poderiam ter sido previstas, e assim prejudicando o desempenho na eficiência do projeto, bem como uma analise nas adaptações baseando-se nesses erros ao dos longos dos anos.  
Embora ainda não tenha tido a oportunidade de participar de alguma atividade na área de pesquisa, sei que tenho as qualidades necessárias para a realização desse projeto, por ser uma pessoa esforçada e dedicada com as atividades na qual eu me dedico. Agradeceria muito se me aceitasse como orientanda, pois essa seria uma grande oportunidade para me aprofundar mais na área na qual eu mais interesso como também acredito que será o primeiro passo para a vida acadêmica na qual eu quero seguir.
Desde já agradeço a atenção, Iriani Jéssica.

### Links

Substituir as lacunas com os links dos seus perfis nas respectivas plataformas:

-  http://lattes.cnpq.br/8596533347836400
- https://orcid.org/0000-0001-5942-9459

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [x] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [ ] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Iriani,

Obrigado pelo contato. Terias interesse numa pesquisa sobre tipologias de fundações tradicionais em casas do planalto Central?

**Comment by Iriani11** [comment]
Boa noite, professor

Sim, tenho interesse sobre o assunto. Gostaria de agradecer pela
oportunidade e também quais seriam os próximos passos.


Em ter., 19 de mai. de 2020 às 15:05, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by p3palazzo** [comment]
Olá Iriani, a pedido de algumas de vocês, agendei uma videoconferência para tirarmos dúvidas sobre o processo de inscrição no Pibic e o uso do GitHub. Será amanhã (sexta-feira) às 15h de Brasília na plataforma Microsoft Teams fornecida pela UnB. Quem é estudante da própria UnB encontrará o convite no seu e-mail @aluno.unb.br ou fazendo login com este mesmo e-mail em https://teams.microsoft.com. Por favor confirme recebimento.

**Comment by Iriani11** [comment]
Obrigada, professor, ficarei no aguardo.

Em qui., 21 de mai. de 2020 às 12:26, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by p3palazzo** [comment]
Olá @Iriani11, peço desculpas pela demora em formular o plano de trabalho. Está disponível para edição [aqui](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-fundacoes.md). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/). Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by Iriani11** [comment]
Boa tarde, professor
Peço desculpas por ainda não ter entradado na reunião, eu estou tento problemas para fazer o login.

**Comment by Iriani11** [comment]
Professor, infelizmente não estou conseguindo acessar Microsoft Teams. Gostaria de saber se há a possibilidade de entrar em contato por outro meio. 
Peço desculpas novamente.
