### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by tainaabreu** [dmcpatrimonio/arqtrad#2]
Brasília, 20 de março de 2020.

Olá,
Venho por meio desta carta, demonstrar meu interesse em participar deste projeto de pesquisa Clássico, tradicional, eclético: arquitetura brasileira no longo século XIX, coordenado pelo professor e pesquisador Pedro Paulo Palazzo.
Meu desejo nessa vaga surge pelo fato de que sou muito curiosa e me sinto satisfeita em descobrir coisas novas sobre vários assuntos, em especial História. É fascinante aprender sobre o passado e seus costumes. Quero adquirir essa experiencia pois me sinto na obrigação de, como estudante de uma universidade pública, experimentar esse tipo de oportunidade dentro da graduação e claro, agregar ao meu currículo, pois sei que é relevante para meu futuro.
Me encontro no 8° semestre e estou estudando matérias que considero relevante para essa pesquisa, as quais são Arquitetura e Urbanismo no Brasil Contemporâneo e Arquitetura e Urbanismo da Atualidade, então creio que terei uma boa bagagem para a pesquisa.

Atenciosamente, Tainá Lourenço.

### Links

- http://lattes.cnpq.br/3323229615714709 
- https://orcid.org/0000-0002-0167-6024

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [ ] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [X] Distribuições da morada eclética em Goiás
- [X] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Tainá, Obrigado pelo interesse. No final deste mês retorno o contato. Caso tenhas qualquer dúvida ou informação adicional, não hesites em adicionar um comentário nesta página.

**Comment by p3palazzo** [comment]
Olá Iriani, a pedido de algumas de vocês, agendei uma videoconferência para tirarmos dúvidas sobre o processo de inscrição no Pibic e o uso do GitHub. Será amanhã (sexta-feira) às 15h de Brasília na plataforma Microsoft Teams fornecida pela UnB. Quem é estudante da própria UnB encontrará o convite no seu e-mail @aluno.unb.br ou fazendo login com este mesmo e-mail em https://teams.microsoft.com. Por favor confirme recebimento.

**Comment by p3palazzo** [comment]
Olá Tainá, a pedido de algumas de vocês, agendei uma videoconferência para tirarmos dúvidas sobre o processo de inscrição no Pibic e o uso do GitHub. Será amanhã (sexta-feira) às 15h de Brasília na plataforma Microsoft Teams fornecida pela UnB. Quem é estudante da própria UnB encontrará o convite no seu e-mail @aluno.unb.br ou fazendo login com este mesmo e-mail em https://teams.microsoft.com. Por favor confirme recebimento.

**Comment by tainaabreu** [comment]
Confirmado. Obrigada.

Em qui, 21 de mai de 2020 às 12:31, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by p3palazzo** [comment]
Olá @tainaabreu,

Peço desculpas pela demora em formular o teu plano de trabalho. Em consulta com a Supac (Subsecretaria do Patrimônio Cultural) do GDF, definimos a fazenda Velha como objeto de estudo prioritário. O rascunho está disponível para edição [aqui](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-fazvelha.md). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/). Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)
