### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by maria-araujo** [dmcpatrimonio/arqtrad#3]
### Carta de motivação

A trajetória acadêmica é uma jornada de amadurecimento. É tempo de aprender a fazer gestão de tempo e expandir todas as possibilidades. Nos últimos meses eu tenho refletido muito sobre o meu caminhar na faculdade de Arquitetura e Urbanismo, sobre as minhas motivações e meus passos. 

Mais recentemente estive imersa na minha experiência com muitos temas de urbanismo, mapas, legislações, georreferenciamentos, AutoCAD, regularizações e afins - estive estagiando nos últimos dois anos na CODHAB, um período enriquecedor. Ao me aproximar do término dessa fase, tem me ocorrido o ímpeto de explorar outras possibilidades, partindo do que pude aprender nessa. Tenho tido vontade de explorar escalas diferentes, fazer mais leituras, mudar de ambiente, me debruçar em novos temas e pontos de vista e aprender mais. 

A cadeira de Teoria e História aos poucos tem me despertado profundo interesse, em perceber como ela se conecta a uma memória maior, aos avanços, aos pequenos e grandes acontecimentos que formam a totalidade. Por fim, a tudo que permeia a arquitetura e o urbanismo, que, no momento que se consolidam, já são história. Eu percebi que aqui entendo melhor tudo que aprendo nas outras matérias. Sempre saio de uma aula ou leitura com um sentimento satisfatório de ter ampliado meu conhecimento sobre coisas que recorrentemente aparecem como fatos em outras cadeiras, isentas e distantes de seus processos e transformações ao longo do tempo. Também foi aqui que aprendi a ter a leitura como um hábito necessário, para onde recorro, ávida pela motivação e empolgação de encontrar entendimento. 

Eis que, no meio dessa epifania, ainda tentando descobrir como caminhar junto dela, quais seriam meus próximos passos para aplicá-la e como me organizar nessa nova etapa para ter o melhor aproveitamento, me apareceu a possibilidade desta pesquisa, muito atrativa aos meus olhos ao encaixar perfeitamente em minhas presentes ambições. Nela, espero resultados que possam demonstrar meu entusiasmo com a pesquisa e com o aprendizado e que façam com que outras pessoas também possam experimentá-lo, servindo-as de inspiração. 

Atenciosamente,
Maria Isabela

### Links

- http://lattes.cnpq.br/2735374796963447
- https://orcid.org/0000-0002-3270-4219

### Plano de trabalho

- [ ] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [x] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Maria, obrigado pelo interesse e pela carta detalhada. Darei um retorno na próxima semana.

**Comment by p3palazzo** [comment]
Olá Maria, a pedido de algumas de vocês, agendei uma videoconferência para tirarmos dúvidas sobre o processo de inscrição no Pibic e o uso do GitHub. Será amanhã (sexta-feira) às 15h de Brasília na plataforma Microsoft Teams fornecida pela UnB. Quem é estudante da própria UnB encontrará o convite no seu e-mail @aluno.unb.br ou fazendo login com este mesmo e-mail em https://teams.microsoft.com. Por favor confirme recebimento.

**Comment by p3palazzo** [comment]
Olá @maria-araujo,

Peço desculpas pela demora em formular o teu plano de trabalho — estava repensando todo o projeto de pesquisa tendo em vista as novas diretrizes do CNPq. Disponibilizo [um primeiro rascunho](https://github.com/dmcpatrimonio/arqtrad/blob/master/pibic21-camaras.md), por enquanto só com os objetivos. Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo. Observa também o edital postado [aqui](http://proic.unb.br/). Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by maria-araujo** [comment]
Confirmo recebimento!
