### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by carolsanpa** [dmcpatrimonio/arqtrad#5]
### Carta de motivação

Por este meio, apresento meu interesse em participar do projeto de pesquisa ‘Clássico, tradicional, eclético: arquitetura brasileira no longo século XIX’, coordenado por Pedro Paulo Palazzo, do grupo de pesquisa Documentação, Modelagem e Conservação do Patrimônio.

Me chamo Ana Caroline, tenho 21 anos, sou aluna graduanda do 8º período em Arquitetura e Urbanismo na Universidade de Brasília, e atualmente faço estágio no Senado Federal. 

O meu interesse no projeto de pesquisa se deu tanto pela oportunidade de adquirir um conhecimento mais aprofundado na arquitetura brasileira indicada, pelos meios de produção textual e obras construídas no período em estudo, quanto pelos planos de trabalho relacionados. No semestre que cursei a disciplina Arquitetura e Urbanismo no Brasil Colônia e Império, em 1º/2019, tive a oportunidade de fazer em um dos trabalhos o levantamento técnico da Casa de Cora Coralina. Mesmo com a impossibilidade de um levantamento fidelíssimo por motivos de localização, pude desenvolver um levantamento aproximado a partir de pesquisas teóricas e visuais. Nesse mesmo semestre e disciplina, também desenvolvi um trabalho de representação de esquadrias do centro histórico de Planaltina, o que me despertou ao fato de que trabalhos práticos solidificam mais o aprendizado teórico que recebemos, além do fato de que elementos e construções ainda existentes, são os mais valiosos meios concretos que temos de caracterização da arquitetura brasileira. Portanto, particularmente tenho um interesse maior pelo plano de trabalho ‘Arqueologia das antigas casas rurais no Distrito Federal e entorno’. Contudo, não havendo a disponibilidade do plano, também me interesso pelo de 'Distribuições da morada eclética em Goiás'.

Atenciosamente, 
Carol. 

### Links

- http://lattes.cnpq.br/3443287356411632
- https://orcid.org/0000-0003-4299-6291

### Plano de trabalho

- [ ] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [x] Distribuições da morada eclética em Goiás
- [x] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Ana Caroline, obrigado pelo interesse e pelo cuidado investido na carta de intenções. Voltarei a entrar em contato logo após a Páscoa.

**Comment by p3palazzo** [comment]
Olá Ana Caroline,

O rascunho do plano de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponível para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/)

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by p3palazzo** [comment]
Olá @carolsanpa, em consulta com a Supac (Subsecretaria do Patrimônio Cultural) do GDF, definimos a fazenda Gama como objeto de estudo específico. Segue link atualizado para o plano de trabalho: https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-gama.md
