### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by flaviarosa** [dmcpatrimonio/arqtrad#6]
### Carta de motivação

Eu, Flávia Rosa de La Plata, estudante da Faculdade de Arquitetura e Urbanismo da Universidade de Brasília no 10º semestre, venho por meio desta carta expressar meu interesse na área de pesquisa, apresentando alguns dos conhecimentos adquiridos ao longo da graduação, e experiência de pesquisa na FAU.

Durante o curso, adquiri conhecimentos em diversos softwares, entre eles o QGIS e BIM, que são pré-requisitos para a candidatura. A experiência adquirida em QGIS se deu por meio das aulas de Projeto Urbanístico e Projeto Urbano, e a de BIM por meio de disciplinas obrigatórias e cursos a parte da faculdade.

Além do conhecimento técnico, também pude participar de um projeto de pesquisa por meio do PIBIC no edital  2017/2018, com tema que remete a arquitetura e urbanismo de viés histórico, "A cidade brasileira do século XIX: Urbanização, arte e crítica na República Velha", também por meio do LabeUrbe. Com essa experiência, despertei o interesse em me aprofundar em novos assuntos e me inserir ainda mais no mundo da pesquisa acadêmica, pois, apesar de já ter tido contato, ainda não me sinto devidamente preparada e habituada com esta área de ensino. 

Portanto, levando essas questões em consideração, despertei o interesse pelo plano de trabalho "Distribuições da morada eclética em Goiás" , pelo fato de ser uma área que já tive a oportunidade de estudar e explorar ao longo da disciplina "Arquitetura e Urbanismo no Brasil Contemporâneo" com a professora Ana Paula Gurgel e por ser um assunto que agrega mais da parte de arquitetura histórica, o que me agrada bastante, levando em consideração que meu último projeto de pesquisa necessitava de uma investigação voltada para a escala urbana. 

Por meio deste breve texto acredito que pude evidenciar um pouco do meu interesse e das minhas habilidades, e acredito que possuo motivação e aptidão para desenvolver o trabalho da melhor forma possível.

### Links

Substituir as lacunas com os links dos seus perfis nas respectivas plataformas:

- http://lattes.cnpq.br/3029180833677009 
- https://orcid.org/0000-0002-8758-9692

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [ ] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [x] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Obrigado, Flávia! Faltou preencher o ORCID...

**Comment by flaviarosa** [comment]
Desculpe, professor, mas o que é ORCID?

Em qui, 2 de abr de 2020 às 13:41, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by p3palazzo** [comment]
Aqui: https://orcid.org/

Depois de criar o perfil, ele vai te dar um link como este na caixa verde:

![Captura de Tela 2020-04-05 às 14 21 32](https://user-images.githubusercontent.com/8295666/78499476-da2db280-7748-11ea-9224-40d4d40f224f.png)

**Comment by flaviarosa** [comment]
Perdão! Aqui está:

https://orcid.org/0000-0002-8758-9692

Torcendo! Abraços.

Em dom, 5 de abr de 2020 às 15:19, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by p3palazzo** [comment]
Olá Flávia,

O rascunho do plano de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponível para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/)

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by p3palazzo** [comment]
Olá Flávia, a pedido de algumas de vocês, agendei uma videoconferência para tirarmos dúvidas sobre o processo de inscrição no Pibic e o uso do GitHub. Será amanhã (sexta-feira) às 15h de Brasília na plataforma Microsoft Teams fornecida pela UnB. Quem é estudante da própria UnB encontrará o convite no seu e-mail @aluno.unb.br ou fazendo login com este mesmo e-mail em https://teams.microsoft.com. Por favor confirme recebimento.

**Comment by p3palazzo** [comment]
Olá @flaviarosa, migrei o teu [plano de trabalho](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-distrib.md) para o projeto de pesquisa Resiliência urbana e acrescentei metodologia e [bibliografia](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-distrib.bib) --- versão legível [aqui](https://dmcpatrimonio.github.io/adaptive-construction/pibic21-distrib/). Peço que aceites o convite que te enviei para participar do grupo @dmcpatrimonio/pibic21 aqui no GitHub, visando a organizar melhor a comunicação.
