### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by JoaoTestiNeto** [dmcpatrimonio/arqtrad#7]
### Carta de motivação

Meu objetivo nesse trabalho é o estudo arquitetônico e urbano através de fotografias da época, mais especificamente da região de Barreiras no oeste baiano que foi fundada oficialmente em 1891, mas que antes disso já se tinha aglomerações urbanas e movimentações sociais. Dessa maneira, o que desejo é pesquisar as bases de plantas cadastrais desde a sua fundação, de que forma e o contexto em que a cidade estava e comparar com os levantamentos cadastrais da atualidade. 
Minha grande dificuldade é a falta de material acadêmico para a pesquisa, ela vai ser produzida através das fotos antigas de autoria do fotografo Napoleão de Matos Macedo que datam dos anos 1920 a 1960 e outras de autores desconhecidos até 1980. As minhas fontes vão ser Ignez Pitta de Almeida (Ignez Pitta) professora barreirense que estudou a vida toda sobre a história de Barreiras e que tem muitas vivencias na cidade, o Museu Municipal de Barreiras que me disponibilizou uma grande parte do material fotográfico e que tem muita informação histórica sobre a cidade e as pessoas mais velhas do centro histórico de Barreiras.
Essa pesquisa pode ajudar muitos arquitetos e urbanistas do futuro a conhecer melhor sobre o histórico arquitetônico de Barreiras, podendo dessa forma planejar edificações respeitando tudo o que a cidade já passou. Na atualidade não se vê planejamentos urbanos e arquitetônicos que respeitem a arquitetura histórica e nem o desenvolvimento urbano em torno do rio Grande.    
É uma pesquisa que envolve também minhas vivencias como barreirense, eu nasci e cresci no centro histórico de Barreiras, onde localizam a maioria dos casarões antigos e ruas estreitas de pedra. É uma pesquisa também sobre o desrespeito do espaço urbano histórico e as invasões abruptas modernas na localidade. 

Cronograma: 

Agosto, setembro e outubro de 2020: coleta de informações histórico arquitetônicas (envolvendo entrevistas), catalogação das fotografias por período e estudo de imagens. 
Novembro de 2020: produção de relatório ou pré entrega de projeto.
Dezembro de 2020, janeiro e fevereiro de 2021: fotografar o centro histórico e fazer os links com as pesquisas já realizadas.
Março, abril, maio, junho de 2021: escrita do projeto e entrevistas finais.
Julho de 2021: entrega de projeto final.     
                
### Links

- http://lattes.cnpq.br/4426176176505648
- https://orcid.org/0000-0001-7192-425X

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [x] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [ ] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezado João, obrigado pelo interesse. Vamos desenvolver um plano de trabalho com base nisso. Já compilaste a lista de fontes (livros e fotos) que descreves aqui? Existe uma base cartográfica de Barreiras?

**Comment by JoaoTestiNeto** [comment]
Oi professor, tenho os textos e fotos sim, são mais de 200 fotos. Eu mando os textos pro senhor por aqui? Isso quer dizer que consegui o pibic? 
[barreiras_v3.pdf](https://github.com/dmcpatrimonio/arqtrad/files/4440407/barreiras_v3.pdf)

**Comment by p3palazzo** [comment]
Ainda estamos pensando em como formular o plano de trabalho, certo? O prazo para inscrições junto ao DPG é final de maio.

**Comment by JoaoTestiNeto** [comment]
Certo, mando os texto então por aqui?

**Comment by p3palazzo** [comment]
Olá João,

O rascunho do plano de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponível para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/)

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by JoaoTestiNeto** [comment]
Boa tarde professor, fiz algumas modificações no rascunho do plano de
trabalho. Não modifiquei nada no objetivo, problema e justificativa, acho
que está bem explicado e claro.
Se puder dar um feedback, fico agradecido desde já.
Um bom final de semana!




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 16 de abr. de 2020 às 21:03, Pedro P. Palazzo <
notifications@github.com> escreveu:

**Comment by JoaoTestiNeto** [comment]
Boa noite, Pedro.

Eu enviei a sugestão de alteração, mas ela não está salvando pra mim.
Queria confirmar se você conseguiu ver.




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sex., 24 de abr. de 2020 às 15:32, Com Testi <jtestineto@gmail.com>
escreveu:
