### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by danielamatias** [dmcpatrimonio/arqtrad#8]
### Carta de motivação

Brasília (DF), 05 de abril de 2020

Prezados,
  Meu nome é Daniela Matias Xavier, estou cursando o 8º semestre em Arquitetura e Urbanismo na Universidade de Brasília. Já cursei as matérias Arquitetura e Urbanismo no Brasil Colônia e Império e Arquitetura e Urbanismo no Brasil contemporâneo, além de estar cursando a matéria Arquitetura e Urbanismo na atualidade. 
  Por meio desta carta, expresso o meu interesse e minhas qualificações em cooperar com o programa de iniciação científica no projeto de pesquisa “Clássico, tradicional, eclético: arquitetura brasileira no longo século XIX”, orientado pelo Prof. Dr. Pedro Paulo Palazzo.
  O meu interesse na pesquisa surge tanto pelo grande desejo em participar de um programa de iniciação científica na área da arquitetura e do urbanismo, quanto pela admiração da história e o que ela pode nos ensinar.
  Minha atração inicial foi pelo tema Módulos e dimensões do parcelamento urbano no Brasil do século XIX, apesar de não me importar em trabalhar em outro tema. Creio que a escolha em qualquer um dos temas propostos me trará enriquecimento pessoal e profissional, além de agregar conhecimentos substanciais da história brasileira em minha graduação.
  Acredito que sou hábil para realizar a pesquisa, porque tenho determinação e entusiasmo para explorar o conteúdo, além de ter um bom domínio em programas BIM e o programa Qgis e esforço para aprender o indispensável a um trabalho de qualidade. Atualmente, estou estagiando no Ministério das Relações Exteriores, um dos meus atributos consiste em arquivar e analisar o conteúdo do acervo de plantas históricas tanto do Palácio do Itamaraty, quanto de postos de embaixadas do exterior. As quais estão inseridas em diferentes malhas urbanas de cidades do mundo, além de diversas embaixadas serem tombadas como patrimônio arquitetônico. Creio que este conhecimento pode agregar no levantamento histórico, redesenho e análise das plantas e fontes cartográficas.
  Por fim, estou ciente da complexidade que a pesquisa envolve e confirmo a minha disposição e determinação em contribuir com o desenvolvimento de um estudo de grande importância para a história arquitetônica e urbanística do Brasil. É deslumbrante a ideia de contribuir com a disseminação do conhecimento e a preservação do passado.

                                                                                                      Cordialmente, Daniela Matias Xavier.

### Links

- http://lattes.cnpq.br/6880371959324159 
- https://orcid.org/0000-0002-7858-9324/print

### Plano de trabalho

- [x] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [ ] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Daniela, obrigado pela candidatura. Se tiveres interesse, podemos também montar um plano de trabalho baseado na documentação arquivística do MRE, tratando, por exemplo, do Palácio no Rio de Janeiro. O que achas?

**Comment by danielamatias** [comment]
Acho super interessante!! A documentação oferece diversas vertentes para pesquisas!

**Comment by danielamatias** [comment]
Creio que um trabalho envolvendo o material arquivístico seria algo de interesse para o próprio Ministério, devido estarmos buscando a melhor organização e apresentação do arquivo para o público.  Recentemente, iniciamos um trabalho que consiste em disseminar o conteúdo, inicialmente por meio de pôsteres e futuramente por prováveis exposições. Então um projeto científico que agregue os arquivos seria de grande rendimento!

**Comment by p3palazzo** [comment]
Olá Daniela,

O rascunho do plano de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponível para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Nossa tarefa agora é completar o plano de trabalho segundo as indicações que já se encontram no próprio arquivo e, se quiseres, também fazer alguma alteração nos objetivos, problema e justificativa. Observa também o edital postado [aqui](http://proic.unb.br/) (Essa é a oportunidade "convencional"; se quiseres trabalhar de fato com os arquivos do Itamaraty, vamos conversando para formular um plano de trabalho especial).

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by danielamatias** [comment]
Ok! Gosto bastante de trabalhar com o tema Módulos e dimensões do parcelamento urbano no Brasil do século XIX ! Vou olhar os links e estudar o que seria interessante alterar ou adicionar!!

**Comment by p3palazzo** [comment]
Ok! A @lusgasser também vai trabalhar nessa linha de urbanismo, portanto vamos pegar esse plano de trabalho e desdobrá-lo em dois.

**Comment by danielamatias** [comment]
Olá professor, eu tenho uma dúvida. Olhei os conteúdos e gostaria de saber se o GitHub vai ser utilizado apenas para propor alterações no plano de trabalho ou será usado durante toda a pesquisa?

**Comment by p3palazzo** [comment]
Depois que os planos de trabalho forem aprovados na seleção da UnB (espero que todos sejam!), vou criar um repositório do GitHub separado para cada um de vocês. A ideia é mantermos uma proposta de dados abertos e colaboração durante o desenvolvimento das pesquisas.
