### ISSUE TITLE
[pibic] Candidatura

### ISSUE THREAD

**Issue by lusgasser** [dmcpatrimonio/arqtrad#9]
### Carta de motivação

Prezados e prezadas,

Sou estudante do sexto semestre do curso de Arquitetura e Urbanismo no Centro Universitário de Brasília, UniCEUB. 

Tenho interesse em participar do grupo de pesquisa Documentação, Modelagem e Conservação do Patrimônio, no projeto de pesquisa “Clássico, tradicional, eclético: arquitetura brasileira no século XIX”, com foco no plano de trabalho “Módulos e dimensões do parcelamento urbano no Brasil do século XIX”.

Atualmente sou estagiária no Ministério das Relações Exteriores na Coordenação de Patrimônio e Arquitetura. Neste estágio ponho em prática minhas habilidades de organização para catalogar o acervo de desenhos arquitetônicos do Palácio do Itmaraty e das Embaixadas e Residências oficiais do Brasil no exterior.

Esta experiência tem sido muito enriquecedora pois graças a ela entendo melhor a importância de preservar e valorizar o Patrimônio histórico e cultural do meu país. Eu acredito que um Patrimônio organizado e prestigiado tem uma influência direta no olhar da sociedade sobre sua própria história e cultura.

Minhas áreas de maior interesse acadêmico são Urbanismo e Teoria e História da Arquitetura e do Urbanismo. As duas disciplinas instigam muita curiosidade em mim pois tenho vontade de compreender a cidade, sua origem, seus diferentes traçados, sua evolução no tempo e os efeitos que a história política, social e econômica tem na urbanização do país. A partir deste estudo tenho a intenção de trabalhar na área buscando soluções aos problemas atuais de habitação, carência de infraestruturas urbanas das cidades brasileiras e de preservação da natureza.

Acredito que este projeto de pesquisa seria muito enriquecedor e de extrema utilidade para mim no futuro, acrescentando conhecimentos, ferramentas de busca e métodos em pesquisa acadêmica.

Agradeço desde já por considerar a minha candidatura.

Atenciosamente,
Luiza Silveira Gasser

### Links

Substituir as lacunas com os links dos seus perfis nas respectivas plataformas:

- http://lattes.cnpq.br/0173440372493928
- https://orcid.org/0000-0002-8625-6837

### Plano de trabalho

Assinalar o plano de trabalho no qual tem mais interesse marcando um 'x' entre os colchetes. Esta resposta tem caráter indicativo e não vinculante.

- [x] Módulos e dimensões do parcelamento urbano no Brasil do século XIX
- [ ] Distribuições da morada eclética em Goiás
- [ ] Arqueologia das antigas casas rurais no Distrito Federal e entorno
- [ ] Casa de cultura de Luziânia

**Comment by p3palazzo** [comment]
Prezada Luiza, nesse trabalho com as residências no exterior por acaso tiveste contato com a pesquisa de doutorado em andamento da Giselle Chaim?

**Comment by lusgasser** [comment]
Olá professor,
Infelizmente não tenho conhecimento dessa pesquisa de doutorado...

**Comment by p3palazzo** [comment]
Olá Luiza,

O rascunho dos planos de trabalho está [aqui](https://dmcpatrimonio.github.io/arqtrad/pibic21-projeto/), e disponíveis para edição [aqui](https://github.com/dmcpatrimonio/arqtrad/). Observa também o edital postado [aqui](http://proic.unb.br/)

Estou te propondo um desafio especial, caso te interesse: desenvolvermos um plano de trabalho baseado nos arquivos do MRE. Ao contrário dos outros planos, deixei o teu em aberto para conversarmos sobre uma direção a tomar. Caso prefiras trabalhar com algo não ligado ao Itamaraty, também podemos redirecionar sem problemas.

A esta altura deves ter recebido outra mensagem com um convite para participar do repositório onde se encontra este arquivo. Podes propor edições ao plano de trabalho diretamente no navegador, ou baixar o repositório no teu computador para editar e gravar com calma. Sugiro começar no YouTube:

1. [Como usar Git e Github na prática: Guia para iniciantes | Mayk Brito](https://youtu.be/2alg7MQ6_sI)
2. [Git e Github para iniciantes](https://youtu.be/UMhskLXJuq4) — é longo mas vale assistir pelo menos os 15 primeiros minutos.
3. [O que é GitHub na prática](https://youtu.be/fG6gl9ne6CE)
4. [O que é Git? O que é versionamento? - Curso de Git e GitHub](https://youtu.be/xEKo29OWILE)

E depois passar para uns tutoriais escritos:

1. [Escreva em Markdown](https://medium.com/cl%C3%A1ssicos-digitais/escreva-em-markdown-fa358c779c61)
2. [Sintaxe básica de escrita e formatação no GitHub](https://help.github.com/pt/github/writing-on-github/basic-writing-and-formatting-syntax)
3. [Como os escritores podem usar o GitHub para armazenar seu trabalho ](https://comofazergeek.blogspot.com/2019/08/como-os-escritores-podem-usar-o-github.html)
4. [Git e Github — Por que e como usar? — Parte 1](https://medium.com/nstech/git-e-github-por-que-e-como-usar-parte-1-fcb98261fde0)
5. [Criar o primeiro repositório usando o GitHub Desktop](https://help.github.com/pt/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop)
6. [Como usar o GitHub?](https://programathor.com.br/blog/como-usar-o-github/)
7. [O editor de texto que eu indico: Atom](https://atom.io/)

**Comment by lusgasser** [comment]
Boa noite professor,

Muito obrigada por considerar abrir uma pesquisa baseada nos arquivos do MRE para mim. Entretanto meu real interesse está em pesquisar sobre o urbanismo das cidades brasileiras no século XIX. Espero que isso não seja um inconveniente.

Como este é o primeiro projeto de pesquisa ao qual me candidato, não conheço muito bem as etapas a seguir. Neste primeiro momento vamos propor um projeto e um plano de trabalho e depois este terá que ser aceito para que possamos seguir em frente?

Obrigada mais uma vez!

**Comment by p3palazzo** [comment]
Certo! Vamos desdobrar o plano de urbanismo em dois, então, pois a @danielamatias também está interessada nele. Quando terminarmos de formular os planos de trabalho, vamos inscrevê-los na seleção que será feita pelo Decanato de Pesquisa e Inovação da UnB.

**Comment by p3palazzo** [comment]
Olá @lusgasser, veja o plano de trabalho a seguir: https://github.com/dmcpatrimonio/arqtrad/blob/master/pibic21-urbanistas.md

Convido-te a contribuir para completarmos a redação do plano a tempo da inscrição.

**Comment by lusgasser** [comment]
Olá @p3palazzo , obrigada pelo contato. 
Estou tendo dificuldades de entender como funciona o Github, mesmo vendo os vídeos, e lendo os textos... E também ainda tenho algumas dúvidas em relação ao projeto de pesquisa, os materiais que vamos usar, as plataformas de trabalho e as dinâmicas.
Eu consegui entrar em contato com o restante dos alunos que passaram neste projeto, e nós gostaríamos de propor uma videoconferência com o senhor para esclarecer nossas dúvidas.
Seria possível? Poderíamos usar as plataformas de encontros virtuais do Gmail, como Google Meets, ou Hangouts.

Agradeço desde já pela compreensão!

**Comment by p3palazzo** [comment]
Tudo bem! É possível editar os textos diretamente no navegador, se te parecer mais fácil. Ainda tenho 3 candidatas para as quais preciso formular novos planos de trabalho, mas penso que podemos marcar uma videoconferência talvez na sexta-feira. O que acham? A UnB fornece a plataforma Teams para utilizarmos, convém? https://teams.microsoft.com/

**Comment by lusgasser** [comment]
Obrigada professor! Estou falando com o restante dos alunos para ver se sexta-feira está bom para todos. Para mim está ótimo. Qual horário seria ideal para o senhor?

**Comment by p3palazzo** [comment]
Às 11h ou 15h (horário de Brasília) cai bem para o meu fuso horário. Por favor me envia (diretamente para o meu e-mail e não respondendo a esta mensagem) o teu endereço de e-mail para que eu possa te adicionar ao grupo do Teams.
